# Couldn't automatically generate a config from your source code.
# This is generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  # ====

  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build an artifact
          command: npx expo export:web
      - aws-s3/sync:
          # arguments: |
          #   --acl public-read --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: web-build
          to: s3://test-bucket-delete-it-00

  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/node:15.0.1
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          # command: '#e.g. ./deploy.sh'
          command: echo 'deploying'

workflows:
  testing:
    jobs:
      - build
      - deploy:
          requires:
            - build
